### ISSUE TITLE
Love Running

### ISSUE THREAD

**Issue by JodyMurray** [JodyMurray/My-first-agile-project#3]
As a **user** I can **suggest a new location for the running event** so that **more people can attend**

**Comment by JodyMurray** [comment]
## Acceptance Criteria:

- Option should be provided for comment section
- Users should be able to see comments with suggestions on page
- After commenting users should vote and choose a location point

**Comment by JodyMurray** [comment]
## Tasks

- [x] Update HTML and CSS to include comment section.
- [ ] Add functionality to upvote or downvote a comment
- [ ] Add HTML and CSS to include news section so users can see the newly updated location for the event
